# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: poker.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'poker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpoker.proto\x12\x08poker5cd\",\n\x0fPoker5cdRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"#\n\x10Poker5cdResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x96\x01\n\x0fPoker5cdService\x12>\n\x05Hello\x12\x19.poker5cd.Poker5cdRequest\x1a\x1a.poker5cd.Poker5cdResponse\x12\x43\n\nHelloAgain\x12\x19.poker5cd.Poker5cdRequest\x1a\x1a.poker5cd.Poker5cdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'poker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POKER5CDREQUEST']._serialized_start=25
  _globals['_POKER5CDREQUEST']._serialized_end=69
  _globals['_POKER5CDRESPONSE']._serialized_start=71
  _globals['_POKER5CDRESPONSE']._serialized_end=106
  _globals['_POKER5CDSERVICE']._serialized_start=109
  _globals['_POKER5CDSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
