# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.pb import poker_pb2 as poker__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in poker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Poker5cdServiceStub(object):
    """エンドポイント定義
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/poker5cd.Poker5cdService/Hello',
                request_serializer=poker__pb2.Poker5cdRequest.SerializeToString,
                response_deserializer=poker__pb2.Poker5cdResponse.FromString,
                _registered_method=True)
        self.HelloAgain = channel.unary_unary(
                '/poker5cd.Poker5cdService/HelloAgain',
                request_serializer=poker__pb2.Poker5cdRequest.SerializeToString,
                response_deserializer=poker__pb2.Poker5cdResponse.FromString,
                _registered_method=True)


class Poker5cdServiceServicer(object):
    """エンドポイント定義
    """

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HelloAgain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Poker5cdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=poker__pb2.Poker5cdRequest.FromString,
                    response_serializer=poker__pb2.Poker5cdResponse.SerializeToString,
            ),
            'HelloAgain': grpc.unary_unary_rpc_method_handler(
                    servicer.HelloAgain,
                    request_deserializer=poker__pb2.Poker5cdRequest.FromString,
                    response_serializer=poker__pb2.Poker5cdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'poker5cd.Poker5cdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('poker5cd.Poker5cdService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Poker5cdService(object):
    """エンドポイント定義
    """

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poker5cd.Poker5cdService/Hello',
            poker__pb2.Poker5cdRequest.SerializeToString,
            poker__pb2.Poker5cdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HelloAgain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poker5cd.Poker5cdService/HelloAgain',
            poker__pb2.Poker5cdRequest.SerializeToString,
            poker__pb2.Poker5cdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
